SELECT
	TRANSACTION_DATE
	, PART_GROUP2
	, SUM(QUANTITY) AS QUANTITY
	, ORG
FROM
	COMM.FCST.NEW_USAGE_ALL_VW (NOLOCK)
WHERE
	PART_GROUP2 IS NOT NULL
AND
	ORG_GROUP2 NOT IN ('CONSIGNED', 'WIRELESS CON', 'SERVICE')
AND
	TRANSACTION_DATE > DATEADD(year, -1, GETDATE())
GROUP BY
	TRANSACTION_DATE
	, PART_GROUP2
	, ORG
ORDER BY
	TRANSACTION_DATE